Web Programlama/WebApplication4.5/Models/ErrorViewModel.cs
using System;

namespace WebApplication4._5.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Web Programlama/WebApplication4.5/Models/Ogrenci.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication4._5.Models
{
    public class Ogrenci
    {
        [Display(Name="Öğrenci Adı:")] 
        public string OgrAd { get; set; }
        public string OgrSoyAd { get; set; }
        public int OgrNo { get; set; }
        public DateTime OgrDogum { get; set; }
        public string OgrSehir { get; set; }

    }
}

Web Programlama/WebApplication4.5/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using WebApplication4._5.Models;

namespace WebApplication4._5.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Web Programlama/WebApplication4.5/Controllers/OgrenciController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication4._5.Models;

namespace WebApplication4._5.Controllers
{
    public class OgrenciController : Controller
    {
        public IActionResult Index()
        {
            ViewBag.sehirler = new List<SelectListItem>() { 
                new SelectListItem { Value = "54", Text = "Sakarya" };
                new SelectListItem { Value = "34", Text = "İstanbul" };
                new SelectListItem { Value = "35", Text = "İzmir" };
                return View();
            }
        }
        public IActionResult Kaydet(Ogrenci Ogr)
        {
            return View();
        }

    }
   
}

Web Programlama/WebApplication4.5/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Web Programlama/WebApplication4.5/Views/Ogrenci/Index.cshtml
@model WebApplication4._5.Models.Ogrenci

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<h4>Ogrenci</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Kaydet" asp-controller="Ogrenci">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="OgrAd" class="control-label"></label>
                <input asp-for="OgrAd" class="form-control" />
                <span asp-validation-for="OgrAd" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OgrSoyAd" class="control-label"></label>
                <input asp-for="OgrSoyAd" class="form-control" />
                <span asp-validation-for="OgrSoyAd" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OgrNo" class="control-label"></label>
                <input asp-for="OgrNo" class="form-control" />
                <span asp-validation-for="OgrNo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OgrDogum" class="control-label"></label>
                <input asp-for="OgrDogum" class="form-control" />
                <span asp-validation-for="OgrDogum" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OgrSehir" class="control-label"></label>
                <input asp-for="OgrSehir" class="form-control" asp-items="ViewBag.sehirler">
                <span asp-validation-for="OgrSehir" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Kaydet" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Web Programlama/WebApplication4.5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication4._5</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication4._5</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - WebApplication4._5 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>